### ISSUE TITLE
Travis CI, code coverage, constructor and import sorts

### ISSUE THREAD

**Issue by hsluoyz** [TecnologiaDeBloques/go-casbin-pg-adapter#1]
Use constructor params instead of env.

**Comment by Vanclief** [comment]
@hsluoyz, apologies for the delay. We had put on hold the casbin implementation. I have just updated the module:

- Utilizes constructor params instead of env. 
- Uses casbin v2

**Comment by hsluoyz** [comment]
@Vanclief thanks! Can you add it to: https://casbin.org/docs/en/adapters ?

**Comment by nafisfaysal** [comment]
@Vanclief @hsluoyz https://github.com/casbin/casbin-pg-adapter updated one.

**Comment by Vanclief** [comment]
Cool, thanks for letting me know! @nafisfaysal 

Just took a look at the updated one, and seems more complete @hsluoyz. Would be better to add that one.

**Comment by hsluoyz** [comment]
Sounds good to me!
